--  Hyperion API
--  Hyperion Monitoring API The monitoring agent is first registered so that the server knows it as well as its security key.  Each host are then registered by a monitoring agent. 
--
--  OpenAPI spec version: 1.0.0
--  Contact: Stephane.Carrez@gmail.com
--
--  NOTE: This package is auto generated by the swagger code generator 3.2.0-SNAPSHOT.
--  https://openapi-generator.tech
--  Do not edit the class manually.
with Helios.Rest.Models;
with Swagger.Clients;
package Helios.Rest.Clients is

   type Client_Type is new Swagger.Clients.Client_Type with null record;

   --  Register a monitoring agent
   --  Register a new monitoring agent in the system
   procedure Register_Agent
      (Client : in out Client_Type;
       Name : in Swagger.UString;
       Ip : in Swagger.UString;
       Agent_Key : in Swagger.UString;
       Result : out Helios.Rest.Models.Agent_Type);

   --  Create a host
   --  Register a new host in the monitoring system
   procedure Create_Host
      (Client : in out Client_Type;
       Name : in Swagger.UString;
       Ip : in Swagger.UString;
       Host_Key : in Swagger.UString;
       Result : out Helios.Rest.Models.Host_Type);

end Helios.Rest.Clients;
